"""
Django settings for liberty_social project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from decouple import config, Csv
from urllib.parse import urlparse, parse_qsl

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

REDIS_URL = config("REDIS_URL", default="redis://127.0.0.1:6379/0")


def get_redis_url_with_ssl():
    """
    Parse REDIS_URL and add SSL parameters if using rediss:// (TLS).
    Celery requires explicit ssl_cert_reqs parameter when using rediss:// URLs.
    """
    redis_url = REDIS_URL
    if redis_url.startswith("rediss://"):
        # Parse the URL
        parsed = urlparse(redis_url)
        # Check if ssl_cert_reqs is already in the query string
        query_params = parse_qsl(parsed.query)
        has_ssl_cert_reqs = any(key == "ssl_cert_reqs" for key, _ in query_params)

        if not has_ssl_cert_reqs:
            # Add ssl_cert_reqs=none for Upstash (CERT_NONE)
            # For production with proper certificates, you might want to use 'required'
            # but Upstash works fine with 'none' for certificate validation
            separator = "&" if parsed.query else "?"
            redis_url = f"{redis_url}{separator}ssl_cert_reqs=none"

    return redis_url


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-qr7)ec(b!*j8d(w_51s=+e)#1hmgv+bx-8(xph5*!xiox5j2vh"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="api.mylibertysocial.com,liberty-backend-alb-343841641.us-east-1.elb.amazonaws.com",
    cast=Csv(),
)


# Application definition

INSTALLED_APPS = [
    # Enable django-cors-headers so frontends (localhost:3000 etc.) can access the API during development.
    # Install with: pip install django-cors-headers
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "whitenoise.runserver_nostatic",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users",
    "main",
    "channels",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "django_filters",
]

MIDDLEWARE = [
    # CorsMiddleware should be as high as possible
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "liberty_social.middleware.UserActivityMiddleware",
]

ROOT_URLCONF = "liberty_social.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "liberty_social.wsgi.application"
ASGI_APPLICATION = "liberty_social.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
            # Use PubSub backend instead of core backend
            # This avoids Lua scripts which ElastiCache Serverless doesn't support
        },
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": 5432,
        "OPTIONS": {
            "connect_timeout": "10",
            "sslmode": "require",
        },
        "CONN_MAX_AGE": 600,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Frontend URL for email links
FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:3000")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"

# email
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "webmaster@localhost")

# Admin email for receiving bug reports / feedback.
# The project previously expected an ADMIN_EMAIL env var in some deployments.
# For convenience (so a developer doesn't have to set an env var), default to
# the requested inbox. Override with ADMIN_EMAIL in environment if desired.
ADMIN_EMAIL = config("ADMIN_EMAIL", "jamesezekiel039@gmail.com")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=100),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=104),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Liberty Social API",
    "DESCRIPTION": "API documentation for Liberty Social application",
    "VERSION": "1.0.0",
}

# CORS - allow frontend origins during development
# Add your frontend origins here (protocol + host + port)
# When CORS_ALLOW_CREDENTIALS is True, we cannot use CORS_ALLOW_ALL_ORIGINS
# We must specify exact origins
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:3000,http://localhost:3001,https://mylibertysocial.com,https://www.mylibertysocial.com",
    cast=Csv(),
)

# If your frontend needs to send cookies/auth credentials set this to True
CORS_ALLOW_CREDENTIALS = config("CORS_ALLOW_CREDENTIALS", default=True, cast=bool)

# Resend email provider integration
# If you set RESEND_API_KEY in your environment, the project will use a small
# Django email backend that sends messages through Resend's API. For local
# development you can leave RESEND_API_KEY empty and Django's console email
# backend will be used instead.
RESEND_API_KEY = config("RESEND_API_KEY")
if RESEND_API_KEY:
    EMAIL_BACKEND = "liberty_social.email_backends.ResendEmailBackend"


STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

FRONTEND_URL = config("FRONTEND_URL")

PUSH_NOTIFICATIONS_ENABLED = config(
    "PUSH_NOTIFICATIONS_ENABLED", default=False, cast=bool
)
FIREBASE_PROJECT_ID = config("FIREBASE_PROJECT_ID", default="")
FIREBASE_CREDENTIALS_JSON = config("FIREBASE_CREDENTIALS_JSON", default="")
FIREBASE_WEB_API_KEY = config("FIREBASE_WEB_API_KEY", default="")
FIREBASE_WEB_APP_ID = config("FIREBASE_WEB_APP_ID", default="")
FIREBASE_WEB_PROJECT_ID = config("FIREBASE_WEB_PROJECT_ID", default=FIREBASE_PROJECT_ID)
FIREBASE_WEB_MESSAGING_SENDER_ID = config(
    "FIREBASE_WEB_MESSAGING_SENDER_ID", default=""
)
FIREBASE_WEB_AUTH_DOMAIN = config("FIREBASE_WEB_AUTH_DOMAIN", default="")
FIREBASE_WEB_STORAGE_BUCKET = config("FIREBASE_WEB_STORAGE_BUCKET", default="")
FIREBASE_WEB_MEASUREMENT_ID = config("FIREBASE_WEB_MEASUREMENT_ID", default="")
FIREBASE_WEB_VAPID_KEY = config("FIREBASE_WEB_VAPID_KEY", default="")

# Get Redis URL with SSL parameters for Celery (if using rediss://)
CELERY_REDIS_URL = get_redis_url_with_ssl()

# Get broker URL from config, defaulting to REDIS_URL with SSL params
broker_url_from_config = config("CELERY_BROKER_URL", default=None)
if broker_url_from_config is None:
    # Use the Redis URL with SSL params added
    CELERY_BROKER_URL = CELERY_REDIS_URL
else:
    # User explicitly set CELERY_BROKER_URL, ensure it has SSL params if needed
    CELERY_BROKER_URL = broker_url_from_config
    if CELERY_BROKER_URL.startswith("rediss://"):
        parsed = urlparse(CELERY_BROKER_URL)
        query_params = parse_qsl(parsed.query)
        if not any(key == "ssl_cert_reqs" for key, _ in query_params):
            separator = "&" if parsed.query else "?"
            CELERY_BROKER_URL = f"{CELERY_BROKER_URL}{separator}ssl_cert_reqs=none"

# Get result backend from config, defaulting to broker URL
result_backend_from_config = config("CELERY_RESULT_BACKEND", default=None)
if result_backend_from_config is None:
    CELERY_RESULT_BACKEND = CELERY_BROKER_URL
else:
    CELERY_RESULT_BACKEND = result_backend_from_config
    if CELERY_RESULT_BACKEND.startswith("rediss://"):
        parsed = urlparse(CELERY_RESULT_BACKEND)
        query_params = parse_qsl(parsed.query)
        if not any(key == "ssl_cert_reqs" for key, _ in query_params):
            separator = "&" if parsed.query else "?"
            CELERY_RESULT_BACKEND = (
                f"{CELERY_RESULT_BACKEND}{separator}ssl_cert_reqs=none"
            )

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_SOFT_TIME_LIMIT = 30

# Additional Celery Redis configuration for SSL
# This ensures proper SSL handling for Upstash Redis
# Note: ssl_cert_reqs in the URL takes precedence, but we set transport options as well
CELERY_BROKER_TRANSPORT_OPTIONS = {}
if CELERY_BROKER_URL.startswith("rediss://"):
    # Set SSL options for broker transport
    # 'none' means CERT_NONE (no certificate verification)
    # For Upstash, this works fine. For stricter security, use 'required'
    CELERY_BROKER_TRANSPORT_OPTIONS["ssl_cert_reqs"] = "none"


# ============================================
# Animal Marketplace Configuration
# ============================================
ANIMAL_MARKETPLACE = {
    # Seller verification expiry time (in days)
    "VERIFICATION_EXPIRY_DAYS": config(
        "ANIMAL_VERIFICATION_EXPIRY_DAYS", default=365, cast=int
    ),
    # Animal listing expiry time (in days) - listings automatically expire if not renewed
    "LISTING_EXPIRY_DAYS": config("ANIMAL_LISTING_EXPIRY_DAYS", default=90, cast=int),
    # Maximum number of photos per listing
    "MAX_PHOTOS_PER_LISTING": config("ANIMAL_MAX_PHOTOS", default=12, cast=int),
    # Risk score thresholds for suspicious activity detection
    "RISK_SCORE_THRESHOLDS": {
        "LOW": 0,  # No suspicious activity
        "MEDIUM": 30,  # Moderate risk factors present
        "HIGH": 60,  # Multiple concerning factors
        "CRITICAL": 85,  # Likely fraudulent listing
    },
    # Suspicious activity types and their risk scores
    "RISK_SCORES": {
        "price_unusually_low": 25,
        "price_unusually_high": 15,
        "multiple_rapid_edits": 20,
        "vague_description": 15,
        "no_vet_documentation": 30,
        "unverified_seller": 40,
        "seller_new_account": 20,
        "multiple_complaints": 50,
        "reported_scam": 100,
    },
    # Seller types for verification workflow
    "SELLER_TYPES": ["individual", "breeder", "shelter", "rescue"],
    # Document verification requirements
    "REQUIRE_ID_DOCUMENT": True,
    "REQUIRE_VET_DOCUMENTATION": True,
    # Auto-approval settings
    "AUTO_APPROVE_VERIFIED_SELLERS": config(
        "ANIMAL_AUTO_APPROVE", default=False, cast=bool
    ),
    # Email notification settings
    "NOTIFY_ON_LISTING_EXPIRY": True,
    "NOTIFY_ON_VERIFICATION_EXPIRY": True,
    "NOTIFY_ON_SUSPICIOUS_ACTIVITY": True,
}
