# Generated by Django 5.2.7 on 2025-11-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_conversation_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="message",
            new_name="main_messag_convers_370a90_idx",
            old_name="main_mess_convers_b9592d_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="main_messag_sender__2d72c8_idx",
            old_name="main_mess_sender_1f2a66_idx",
        ),
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
