# Generated by Django 5.2.7 on 2025-11-15 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_marketplacelisting_status_pageinvite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="category",
            field=models.CharField(
                choices=[
                    ("business", "Business"),
                    ("community", "Community"),
                    ("brand", "Brand"),
                    ("news", "News"),
                    ("restaurant", "Restaurant"),
                    ("entertainment", "Entertainment"),
                    ("hobbies", "Hobbies"),
                    ("work", "Work"),
                    ("associates", "Associates"),
                    ("sports", "Sports"),
                    ("music", "Music"),
                    ("art", "Art"),
                    ("tech", "Technology"),
                    ("lifestyle", "Lifestyle"),
                    ("education", "Education"),
                    ("health", "Health & Wellness"),
                    ("travel", "Travel"),
                    ("food", "Food & Cooking"),
                    ("fashion", "Fashion"),
                    ("games", "Games"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="UserFeedPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_friend_posts", models.BooleanField(default=True)),
                ("show_page_posts", models.BooleanField(default=True)),
                (
                    "preferred_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of preferred page categories for filtering",
                    ),
                ),
                (
                    "show_other_categories",
                    models.BooleanField(
                        default=True,
                        help_text="Show posts from categories not in preferred list",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Feed Preferences",
            },
        ),
    ]
