# Generated by Django 5.2.7 on 2025-11-17 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("main", "0015_alter_page_category_userfeedpreference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReactionPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favorite_emojis",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of favorite emoji strings (up to 10)",
                    ),
                ),
                (
                    "recent_emojis",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of recently used emoji strings (up to 10, ordered by recency)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "User Reaction Preferences",
            },
        ),
        migrations.AlterField(
            model_name="reaction",
            name="reaction_type",
            field=models.CharField(default="👍", max_length=10),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="main_reacti_content_ce5c36_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["user", "-created_at"], name="main_reacti_user_id_427801_idx"
            ),
        ),
        migrations.AddField(
            model_name="userreactionpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reaction_preference",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
