# Generated by Django 5.2.7 on 2025-11-18 18:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_userreactionpreference_alter_reaction_reaction_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "animal_type",
                    models.CharField(
                        choices=[
                            ("dogs", "Dogs"),
                            ("cats", "Cats"),
                            ("birds", "Birds"),
                            ("reptiles", "Reptiles"),
                            ("small_mammals", "Small Mammals"),
                            ("livestock", "Livestock"),
                            ("exotics", "Exotics"),
                            ("adoption_rehoming", "Adoption / Rehoming Only"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("icon_url", models.URLField(blank=True, null=True)),
                ("state_restrictions", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Animal Categories",
                "ordering": ["animal_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["animal_type", "is_active"],
                        name="main_animal_animal__6116fb_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AnimalSellerVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state_code", models.CharField(max_length=2)),
                ("zip_code", models.CharField(max_length=10)),
                ("id_document_url", models.URLField(blank=True, null=True)),
                (
                    "id_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("drivers_license", "Driver's License"),
                            ("passport", "Passport"),
                            ("state_id", "State ID"),
                        ],
                        max_length=50,
                    ),
                ),
                ("breeder_license_url", models.URLField(blank=True, null=True)),
                (
                    "breeder_license_number",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animal_seller_verification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_sellers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Seller Verifications",
            },
        ),
        migrations.CreateModel(
            name="AnimalListing",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("adoption", "Adoption"),
                            ("rehoming", "Rehoming"),
                        ],
                        default="sale",
                        max_length=20,
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=255)),
                ("age_years", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("age_months", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=255)),
                (
                    "special_features",
                    models.TextField(
                        blank=True, help_text="e.g., hypoallergenic, trained, etc."
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "rehoming_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="For adoption/rehoming listings",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("state_code", models.CharField(max_length=2)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "contact_preference",
                    models.CharField(
                        choices=[
                            ("chat", "Chat only"),
                            ("phone", "Phone only"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                (
                    "allow_shipping",
                    models.BooleanField(
                        default=False,
                        help_text="Whether shipping/delivery of animal is allowed",
                    ),
                ),
                (
                    "is_legal_in_state",
                    models.BooleanField(
                        default=True, help_text="Verified as legal in the listing state"
                    ),
                ),
                ("legal_check_date", models.DateTimeField(blank=True, null=True)),
                (
                    "legal_issues",
                    models.TextField(
                        blank=True,
                        help_text="Any legal issues or requirements for this listing",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("held", "Held"),
                            ("sold", "Sold"),
                            ("cancelled", "Cancelled"),
                            ("flagged", "Flagged for Review"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("contact_count", models.PositiveIntegerField(default=0)),
                ("suspicious_activity", models.BooleanField(default=False)),
                (
                    "scam_flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of triggered scam detection flags",
                    ),
                ),
                (
                    "review_note",
                    models.TextField(blank=True, help_text="Admin notes for review"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Listing auto-expires after 90 days",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listings",
                        to="main.animalcategory",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animal_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller_verification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="animal_listings",
                        to="main.animalsellerverification",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Animal Listings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BreederDirectory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breeder_name", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "specialties",
                    models.JSONField(
                        default=list,
                        help_text="List of animal types breeder specializes in",
                    ),
                ),
                (
                    "average_rating",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("featured_until", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("inactive", "Inactive"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breeder_directory",
                        to="main.animalsellerverification",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Breeder Directories",
            },
        ),
        migrations.CreateModel(
            name="SellerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="Rating 1-5 stars",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("comment", models.TextField(blank=True)),
                (
                    "accuracy",
                    models.BooleanField(
                        default=True,
                        help_text="Listing accurately described the animal",
                    ),
                ),
                (
                    "health",
                    models.BooleanField(
                        default=True, help_text="Animal arrived in good health"
                    ),
                ),
                (
                    "communication",
                    models.BooleanField(
                        default=True, help_text="Seller communicated clearly"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_reviews_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_reviews",
                        to="main.animallisting",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animal_reviews_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SuspiciousActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("price_manipulation", "Price Manipulation"),
                            ("high_contact_rate", "High Contact Rate"),
                            ("rapid_relisting", "Rapid Relisting"),
                            ("photo_theft", "Stock Photo Detected"),
                            ("unverified_seller", "Unverified Seller Activity"),
                            ("location_mismatch", "Location Mismatch"),
                            ("banned_species", "Banned Species"),
                            ("multiple_flagging", "Multiple User Flags"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolution_note", models.TextField(blank=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspicious_logs",
                        to="main.animallisting",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Suspicious Activity Logs",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="VetDocumentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "documentation_type",
                    models.CharField(
                        choices=[
                            ("vet_check", "Veterinary Check"),
                            ("vaccination_record", "Vaccination Record"),
                            ("health_certificate", "Health Certificate"),
                            ("unknown", "Health Status Unknown"),
                        ],
                        default="unknown",
                        max_length=50,
                    ),
                ),
                ("document_url", models.URLField(blank=True, null=True)),
                ("document_date", models.DateField(blank=True, null=True)),
                (
                    "unknown_disclaimer",
                    models.BooleanField(
                        default=False,
                        help_text="Seller acknowledges health status is unknown",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vet_documentation",
                        to="main.animallisting",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vet Documentations",
            },
        ),
        migrations.CreateModel(
            name="AnimalListingMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")],
                        default="photo",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "is_stock_photo",
                    models.BooleanField(
                        default=False,
                        help_text="AI detected as stock photo (scam risk)",
                    ),
                ),
                (
                    "stock_photo_confidence",
                    models.FloatField(
                        default=0.0,
                        help_text="Confidence score 0-1.0 for stock photo detection",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="main.animallisting",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Animal Listing Media",
                "ordering": ["order", "uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["listing", "is_primary"],
                        name="main_animal_listing_7dd4ae_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="animalsellerverification",
            index=models.Index(
                fields=["user", "status"], name="main_animal_user_id_815fa3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animalsellerverification",
            index=models.Index(
                fields=["status", "verified_at"], name="main_animal_status_6e6631_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animallisting",
            index=models.Index(
                fields=["category", "status", "-created_at"],
                name="main_animal_categor_c484df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="animallisting",
            index=models.Index(
                fields=["seller", "status"], name="main_animal_seller__b45101_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animallisting",
            index=models.Index(
                fields=["state_code", "status"], name="main_animal_state_c_020c11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animallisting",
            index=models.Index(
                fields=["is_legal_in_state", "status"],
                name="main_animal_is_lega_0964f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="animallisting",
            index=models.Index(
                fields=["suspicious_activity"], name="main_animal_suspici_141f96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sellerreview",
            index=models.Index(
                fields=["seller", "-created_at"], name="main_seller_seller__30ac4a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sellerreview",
            unique_together={("listing", "buyer")},
        ),
        migrations.AddIndex(
            model_name="suspiciousactivitylog",
            index=models.Index(
                fields=["listing", "is_resolved"], name="main_suspic_listing_ba54f2_idx"
            ),
        ),
    ]
