# Generated by Django 5.2.7 on 2025-11-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_animalcategory_animalsellerverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerreview',
            name='evidence_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
