# Generated by Django 5.2.7 on 2025-12-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_adminactionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationparticipant",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
