# Generated by Django 5.2.7 on 2025-12-12 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_add_is_archived_to_conversation_participant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "call_type",
                    models.CharField(
                        choices=[("voice", "Voice"), ("video", "Video")],
                        default="voice",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiating", "Initiating"),
                            ("ringing", "Ringing"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("missed", "Missed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="initiating",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Call duration in seconds"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "caller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Link call to a conversation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="main.conversation",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["caller", "-started_at"],
                        name="main_call_caller__afeb97_idx",
                    ),
                    models.Index(
                        fields=["receiver", "-started_at"],
                        name="main_call_receive_8621dd_idx",
                    ),
                    models.Index(
                        fields=["status", "-started_at"],
                        name="main_call_status_9c9b79_idx",
                    ),
                ],
            },
        ),
    ]
