# Generated by Django 5.2.7 on 2026-02-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_add_blur_explicit_toggle"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="appeal",
            new_name="main_appeal_status_167e36_idx",
            old_name="main_appea_status_4edb45_idx",
        ),
        migrations.RenameIndex(
            model_name="compliancelog",
            new_name="main_compli_layer_7ca028_idx",
            old_name="main_compl_layer_9a5f4d_idx",
        ),
        migrations.RenameIndex(
            model_name="compliancelog",
            new_name="main_compli_created_f80ba3_idx",
            old_name="main_compl_created_2e63f4_idx",
        ),
        migrations.RenameIndex(
            model_name="contentclassification",
            new_name="main_conten_content_744873_idx",
            old_name="main_conte_content_c6f5b4_idx",
        ),
        migrations.RenameIndex(
            model_name="contentclassification",
            new_name="main_conten_created_8a6754_idx",
            old_name="main_conte_created_7b9155_idx",
        ),
        migrations.RenameIndex(
            model_name="moderationaction",
            new_name="main_modera_content_d7509b_idx",
            old_name="main_moder_content_25ea13_idx",
        ),
        migrations.RenameIndex(
            model_name="moderationaction",
            new_name="main_modera_layer_b0c008_idx",
            old_name="main_moder_layer_1d07d1_idx",
        ),
        migrations.RenameIndex(
            model_name="moderationaction",
            new_name="main_modera_created_f11387_idx",
            old_name="main_moder_created_3bcba8_idx",
        ),
    ]
