# Generated by Django 5.2.7 on 2026-02-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_add_profanity_redaction"),
        (
            "main",
            "0029_rename_main_appea_status_4edb45_idx_main_appeal_status_167e36_idx_and_more",
        ),
    ]

    operations = []
