# Generated by Django 5.2.7 on 2025-10-29 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('12e28b98-c570-41be-9416-a074f6851f62'), primary_key=True, serialize=False, unique=True, verbose_name='User ID'),
        ),
    ]
