# Generated by Django 5.2.7 on 2025-10-30 05:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='user',
            new_name='to_user',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('9d5744cd-c63e-43bb-a27a-8834c84c2581'), primary_key=True, serialize=False, unique=True, verbose_name='User ID'),
        ),
    ]
