# Generated by Django 5.2.7 on 2025-11-17 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_dismissedsuggestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendshipHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("added", "Added"), ("removed", "Removed")],
                        max_length=20,
                    ),
                ),
                (
                    "removal_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unfriended_by_user", "You unfriended them"),
                            ("unfriended_by_friend", "They unfriended you"),
                            ("both_mutual", "Mutual removal"),
                        ],
                        help_text="Only filled when action is 'removed'",
                        max_length=30,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendship_history_friend",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendship_history_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Friendship Histories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="users_frien_user_id_c45edd_idx",
                    ),
                    models.Index(
                        fields=["user", "action"], name="users_frien_user_id_6f7d24_idx"
                    ),
                ],
            },
        ),
    ]
