# Generated by Django 5.2.7 on 2025-11-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_friendshiphistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(default=False, verbose_name="Is Online"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Activity"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Seen"),
        ),
    ]
