# Generated by Django 5.2.7 on 2025-11-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_is_online_user_last_activity_user_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Activity"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Last Seen"),
        ),
    ]
