# Generated by Django 5.2.7 on 2025-12-10 11:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_accountdeletionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_passkey",
            field=models.BooleanField(
                default=False,
                help_text="Whether user has registered a passkey",
                verbose_name="Has Passkey",
            ),
        ),
        migrations.CreateModel(
            name="PasskeyCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Credential ID",
                    ),
                ),
                (
                    "credential_id",
                    models.TextField(
                        db_index=True,
                        help_text="Base64-encoded credential ID from WebAuthn",
                        unique=True,
                        verbose_name="Credential ID",
                    ),
                ),
                (
                    "public_key",
                    models.TextField(
                        help_text="Base64-encoded public key from WebAuthn",
                        verbose_name="Public Key",
                    ),
                ),
                (
                    "sign_count",
                    models.BigIntegerField(
                        default=0,
                        help_text="Number of times this credential has been used",
                        verbose_name="Sign Count",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="User-friendly name for the device (e.g., 'iPhone 15', 'Chrome on Mac')",
                        max_length=200,
                        null=True,
                        verbose_name="Device Name",
                    ),
                ),
                (
                    "device_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional device information (OS, browser, user agent, etc.)",
                        verbose_name="Device Info",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this passkey was last used",
                        null=True,
                        verbose_name="Last Used At",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this passkey",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkey_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Passkey Credential",
                "verbose_name_plural": "Passkey Credentials",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="users_passk_user_id_f5938c_idx",
                    ),
                    models.Index(
                        fields=["credential_id"], name="users_passk_credent_f3ad68_idx"
                    ),
                ],
            },
        ),
    ]
