# Generated by Django 5.2.7 on 2025-12-11 00:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_has_passkey_passkeycredential"),
    ]

    operations = [
        migrations.AddField(
            model_name="passkeycredential",
            name="device_removed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this device was removed (soft delete)",
                null=True,
                verbose_name="Device Removed At",
            ),
        ),
        migrations.AddField(
            model_name="passkeycredential",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address when passkey was registered",
                null=True,
                verbose_name="IP Address",
            ),
        ),
        migrations.AddField(
            model_name="passkeycredential",
            name="last_seen_ip",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address from last authentication",
                null=True,
                verbose_name="Last Seen IP",
            ),
        ),
        migrations.AddField(
            model_name="passkeycredential",
            name="last_seen_location",
            field=models.CharField(
                blank=True,
                help_text="Location from last authentication",
                max_length=200,
                null=True,
                verbose_name="Last Seen Location",
            ),
        ),
        migrations.AddField(
            model_name="passkeycredential",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Approximate location (city, country) when registered",
                max_length=200,
                null=True,
                verbose_name="Location",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="account_locked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the account was locked",
                null=True,
                verbose_name="Account Locked At",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for account lock",
                null=True,
                verbose_name="Locked Reason",
            ),
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Event ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("login_failed", "Login Failed"),
                            ("logout", "Logout"),
                            ("passkey_registered", "Passkey Registered"),
                            ("passkey_removed", "Passkey Removed"),
                            ("device_removed", "Device Removed"),
                            ("session_revoked", "Session Revoked"),
                            ("account_locked", "Account Locked"),
                            ("account_unlocked", "Account Unlocked"),
                            ("password_changed", "Password Changed"),
                        ],
                        help_text="Type of security event",
                        max_length=50,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of the event",
                        verbose_name="Description",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address where event occurred",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Browser/client user agent string",
                        null=True,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional event data (device_id, session_id, etc.)",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User associated with this event (null for system events)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Event",
                "verbose_name_plural": "Security Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="users_secur_user_id_f93b37_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="users_secur_event_t_e5448a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Session ID",
                    ),
                ),
                (
                    "device_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Associated passkey credential ID if authenticated via passkey",
                        null=True,
                        verbose_name="Device ID",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="Device name from passkey or user agent",
                        max_length=200,
                        null=True,
                        verbose_name="Device Name",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address when session was created",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Approximate location (city, country)",
                        max_length=200,
                        null=True,
                        verbose_name="Location",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Browser/client user agent string",
                        null=True,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time this session was used",
                        verbose_name="Last Activity",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this session was revoked",
                        null=True,
                        verbose_name="Revoked At",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "ordering": ["-last_activity"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_activity"],
                        name="users_sessi_user_id_4c0de0_idx",
                    ),
                    models.Index(
                        fields=["device_id"], name="users_sessi_device__dfea26_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="History ID",
                    ),
                ),
                (
                    "device_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Associated passkey credential ID if authenticated via passkey",
                        null=True,
                        verbose_name="Device ID",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="Device name",
                        max_length=200,
                        null=True,
                        verbose_name="Device Name",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address when login occurred",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Approximate location (city, country)",
                        max_length=200,
                        null=True,
                        verbose_name="Location",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Browser/client user agent string",
                        null=True,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "authentication_method",
                    models.CharField(
                        choices=[("password", "Password"), ("passkey", "Passkey")],
                        default="password",
                        help_text="Method used to authenticate",
                        max_length=50,
                        verbose_name="Authentication Method",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the session ended (logout or expiry)",
                        null=True,
                        verbose_name="Ended At",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who logged in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session History",
                "verbose_name_plural": "Session Histories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="users_sessi_user_id_dd1b9c_idx",
                    )
                ],
            },
        ),
    ]
