# Generated by Django 5.2.7 on 2025-12-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_passkeycredential_device_removed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="token_jti",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="JWT token ID (jti) to identify the session",
                max_length=255,
                null=True,
                verbose_name="Token JTI",
            ),
        ),
    ]
