# Generated by Django 5.2.7 on 2025-12-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_session_token_jti"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="refresh_token_jti",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="JWT refresh token ID (jti) to blacklist tokens when revoking sessions",
                max_length=255,
                null=True,
                verbose_name="Refresh Token JTI",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="token_jti",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="JWT access token ID (jti) to identify the session",
                max_length=255,
                null=True,
                verbose_name="Token JTI",
            ),
        ),
    ]
